---
title: Visvoer
hero_image: images/banner.png
description: Bestuur een vis met je stem en leid hem naar het voedsel
version: 1
listed: true
copyedit: false
last_tested: "2024-06-04"
steps:
  - title: Wat ga je maken
  - title: Het project opzetten
    completion:
    - engaged
  - title: Achtergrondgeluid
  - title: Neem de aanwijzingen op
  - title: Train het model
  - title: Verplaats de vis
    completion:
    - internal
  - title: Uitdaging
    challenge: true
  - title: Wat kun je verder nog doen?
    completion:
    - external
