title: Τροφή για ψάρια
hero_image: images/banner.png
description: Έλεγξε ένα ψάρι χρησιμοποιώντας μόνο τη φωνή σου και κατεύθυνέ το προς την τροφή
version: 1
listed: true
copyedit: false
last_tested: "2024-06-04"
steps:
  - title: Τι θα φτιάξεις
  - title: Ρύθμιση του έργου
    completion:
    - engaged
  - title: Background noise (Θόρυβος περιβάλλοντος)
  - title: Καταγραφή κατευθύνσεων
  - title: Εκπαίδευση του μοντέλου
  - title: Μετακίνηση του ψαριού
    completion:
    - internal
  - title: Πρόκληση
    challenge: true
    completion:
    - external
